# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EwcckGEhnxR785agExBX6BvoEJWkeXhD
"""

import streamlit as st

st.title("💰 AI Financial System")
st.write("Welcome to the dashboard")

col1, col2 = st.columns(2)

with col1:
    st.header("Fraud Detection")

with col2:
    st.header("Credit Risk")

st.header("🛡️ Fraud Detection")

amount = st.number_input("Enter Transaction Amount", value=1000)

if st.button("Check Fraud"):
    if amount > 5000:
        st.error("HIGH RISK 🚨")
    else:
        st.success("LOW RISK ✅")


st.header("💳 Credit Risk")

income = st.number_input("Monthly Income", value=5000)
score = st.number_input("Credit Score", value=600)

if st.button("Check Credit"):
    if score > 650:
        st.success("APPROVED ✅")
    else:
        st.error("REJECTED ❌")


st.header("📈 Market Prediction")

value = st.number_input("Input Value", value=10)

if st.button("Predict Market"):
    st.success("Trend: UP 📈")
    st.info("Change: +3%")


st.header("📰 News Analysis")

text = st.text_input("Enter News")

if st.button("Analyze"):
    if "crisis" in text:
        st.error("NEGATIVE 😟")
    else:
        st.success("POSITIVE 😊")


menu = st.sidebar.selectbox("Choose Module", [
    "Fraud", "Credit", "Market", "News"
])